"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:os_bg)\
$os\
$username\
[](bg:directory_bg fg:os_bg)\
$directory\
[](fg:directory_bg bg:git_bg)\
$git_branch\
$git_status\
[](fg:git_bg bg:language_bg)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:language_bg bg:end)\
[ ](fg:end)\
$line_break$character"""

palette = 'ika'

[palettes.ika]
red = "#f38ba8"
green = "#a6e3a1"
os_bg = "#A3443D"
username_bg = "#A3443D"
directory_bg = "#4E729E"
git_bg = "#6A8AB5"
language_bg = "#858e9b"
end = "#4E729E"
base = "#bfccde"
text = "#bfccde"


[os]
disabled = false
style = "bg:os_bg fg:text"

[os.symbols]
Arch = "󰣇"

[username]
show_always = true
style_user = "fg:text bg:username_bg"
style_root = "fg:text bg:username_bg"
format = '[ $user ]($style)'

[directory]
style = "fg:text bg:directory_bg"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"yzlm" = "󰲋 "

[git_branch]
symbol = ""
format = '[[ $symbol $branch ](fg:base bg:git_bg)]($style)'

[git_status]
format = '[[($all_status$ahead_behind )](fg:base bg:git_bg)]($style)'

[nodejs]
symbol = ""
style = "bg:language_bg"
format = '[[ $symbol( $version) ](fg:base bg:language_bg)]($style)'

[c]
symbol = " "
style = "bg:language_bg"
format = '[[ $symbol( $version) ](fg:base bg:language_bg)]($style)'

[rust]
symbol = ""
style = "bg:language_bg"
format = '[[ $symbol( $version) ](fg:base bg:language_bg)]($style)'

[golang]
symbol = ""
style = "bg:language_bg"
format = '[[ $symbol( $version) ](fg:base bg:language_bg)]($style)'

[php]
symbol = ""
style = "bg:language_bg"
format = '[[ $symbol( $version) ](fg:base bg:language_bg)]($style)'

[java]
symbol = " "
style = "bg:language_bg"
format = '[[ $symbol( $version) ](fg:base bg:language_bg)]($style)'

[kotlin]
symbol = ""
style = "bg:language_bg"
format = '[[ $symbol( $version) ](fg:base bg:language_bg)]($style)'

[haskell]
symbol = ""
style = "bg:language_bg"
format = '[[ $symbol( $version) ](fg:base bg:language_bg)]($style)'

[python]
symbol = ""
style = "bg:language_bg"
format = '[[ $symbol( $version) ](fg:base bg:language_bg)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:creen)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:lavender)'
